"use client";
import Link from "next/link"; import { ArrowLeft, Printer, ShieldCheck } from "lucide-react"; import { QRCodeSVG } from "qrcode.react"; import { useCallback,useEffect,useState,type ReactNode } from "react";
import { buildTicketVerificationUrl } from "@/components/booking/ticket/ticketClient"; import { useLanguage } from "@/i18n/LanguageProvider"; import { formatStaffDate } from "@/i18n/formatters"; import { formatBookingDateTime } from "@/components/admin/bookings/bookingPresentation"; import { cabinKey, statusKey } from "@/components/admin/tickets/ticketOperationsPresentation"; import type { PrintableTicketOperationsDetail,TicketOperationsDetail } from "@/lib/admin/ticketOperationsTypes"; import "./ticketOperations.css";
const Section=({n,title,children}:{n:string;title:string;children:ReactNode})=><section className="xto-detail-section"><h2><span>{n} /</span>{title}</h2>{children}</section>; const Fact=({label,children}:{label:string;children:ReactNode})=><div className="xto-fact"><span>{label}</span><strong>{children}</strong></div>;
export function TicketDetailWorkspace({ticketNumber,canPrint}:{ticketNumber:string;canPrint:boolean}){
 const {locale,t}=useLanguage();const [detail,setDetail]=useState<TicketOperationsDetail|null>(null);const [printData,setPrintData]=useState<PrintableTicketOperationsDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<number|null>(null);const [printing,setPrinting]=useState(false);const [printError,setPrintError]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await fetch(`/admin/api/tickets/${encodeURIComponent(ticketNumber)}`,{credentials:"same-origin",cache:"no-store",signal});if(!r.ok)throw r.status;return r.json() as Promise<TicketOperationsDetail>},[ticketNumber]);
 useEffect(()=>{const c=new AbortController();load(c.signal).then(setDetail).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(typeof e==="number"?e:503)}).finally(()=>setLoading(false));return()=>c.abort()},[load]);
 const print=async()=>{setPrinting(true);setPrintError(false);try{const r=await fetch(`/admin/api/tickets/${encodeURIComponent(ticketNumber)}/print`,{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json() as PrintableTicketOperationsDetail;setPrintData(data);window.setTimeout(()=>window.print(),50)}catch{setPrintError(true)}finally{setPrinting(false)}};
 if(loading)return <p className="xto-state" role="status">{t("ticketOperations.loading")}</p>;if(error||!detail)return <div className="xto-state is-error" role="alert"><p>{t(error===404?"ticketOperations.notFound":error===401?"ticketOperations.sessionExpired":error===403?"ticketOperations.forbidden":"ticketOperations.error")}</p><button onClick={()=>location.reload()}>{t("ticketOperations.retry")}</button></div>;
 const fmt=(v:string|null)=>v?formatBookingDateTime(v,locale):t("ticketOperations.unavailable"); const cancelled=detail.ticketStatus==="CANCELLED"; const flightCancelled=detail.journey.flightStatus==="CANCELLED";
 return <article className={`xto-shell xto-detail ${cancelled?"is-cancelled":""}`}><Link className="xto-back" href="/admin/tickets"><ArrowLeft aria-hidden="true"/>{t("ticketOperations.back")}</Link><header className="xto-ticket-head"><div><p>{t("ticketOperations.terminal")}</p><h1>{detail.ticketNumber}</h1><span className={`xto-chip ${cancelled?"is-cancelled":""}`}>{t(statusKey(detail.ticketStatus))}</span></div><div><strong>{detail.journey.flightNumber}</strong><span>{detail.journey.originCode} → {detail.journey.destinationCode}</span><time dateTime={detail.journey.travelDate}>{formatStaffDate(detail.journey.travelDate,locale)}</time></div></header>
 {cancelled?<div className="xto-cancelled-banner" role="status">{t("ticketOperations.cancelledNotice")}</div>:null}{flightCancelled?<aside className="xto-flight-cancelled" role="alert"><strong>{t("ticketOperations.flightCancelledTitle")}</strong><span>{t("ticketOperations.flightCancelledMessage")}</span></aside>:null}<div className="xto-detail-grid">
 <Section n="01" title={t("ticketOperations.ticket")}><div className="xto-facts"><Fact label={t("ticketOperations.ticketNumber")}>{detail.ticketNumber}</Fact><Fact label={t("ticketOperations.ticketStatus")}>{t(statusKey(detail.ticketStatus))}</Fact><Fact label={t("ticketOperations.issuedAt")}>{fmt(detail.issuedAt)}</Fact><Fact label={t("ticketOperations.cancelledAt")}>{fmt(detail.cancelledAt)}</Fact></div></Section>
 <Section n="02" title={t("ticketOperations.passengers")}><div className="xto-passengers">{detail.passengers.map(p=><div key={p.ordinal}><span>{String(p.ordinal).padStart(2,"0")}</span><strong>{p.displayName}</strong><small>{t(`ticketOperations.passengerTypeName.${p.passengerType.toLowerCase() as "adult"|"child"|"infant"}`)} · {t(`ticketOperations.genderName.${p.gender.toLowerCase() as "male"|"female"|"unspecified"}`)}</small><b>{p.seat??t("ticketOperations.noSeat")}</b></div>)}</div></Section>
 <Section n="03" title={t("ticketOperations.journey")}><div className="xto-facts"><Fact label={t("ticketOperations.flightNumber")}>{detail.journey.flightNumber}</Fact><Fact label={t("ticketOperations.route")}>{detail.journey.originCode} → {detail.journey.destinationCode}</Fact><Fact label={t("ticketOperations.departure")}>{formatStaffDate(detail.journey.travelDate,locale)} · {detail.journey.departureTime??t("ticketOperations.unavailable")}</Fact><Fact label={t("ticketOperations.timeZone")}>{detail.journey.originTimeZone??t("ticketOperations.unavailable")}</Fact><Fact label={t("ticketOperations.flightStatus")}>{t(statusKey(detail.journey.flightStatus))}</Fact></div></Section>
 <Section n="04" title={t("ticketOperations.travelProduct")}><div className="xto-facts"><Fact label={t("ticketOperations.cabin")}>{t(cabinKey(detail.journey.cabin))}</Fact><Fact label={t("ticketOperations.seat")}>{detail.passengers.map(p=>p.seat).filter(Boolean).join(" · ")}</Fact></div></Section>
 <Section n="05" title={t("ticketOperations.booking")}><div className="xto-facts"><Fact label={t("ticketOperations.bookingReference")}>{detail.bookingReference}</Fact><Fact label={t("ticketOperations.bookingStatus")}>{t(statusKey(detail.bookingStatus))}</Fact><Fact label={t("ticketOperations.paymentStatus")}>{t(statusKey(detail.paymentStatus))}</Fact><Fact label={t("ticketOperations.refundStatus")}>{detail.refundStatus?t(statusKey(detail.refundStatus)):t("ticketOperations.unavailable")}</Fact></div></Section>
 <Section n="06" title={t("ticketOperations.document")}><div className="xto-document"><div><ShieldCheck aria-hidden="true"/><strong>{t("ticketOperations.documentTitle")}</strong><span>{t("ticketOperations.documentCopy")}</span></div>{printData?<div className="xto-qr" role="img" aria-label={t("ticketOperations.qrLabel")}><QRCodeSVG value={buildTicketVerificationUrl(printData.qrToken)} size={152} title={t("ticketOperations.qrLabel")}/><small>{t("ticketOperations.qrContext")}</small></div>:null}</div>{cancelled?<p className="xto-print-warning">{t("ticketOperations.cancelledPrint")}</p>:canPrint?<button className="xto-print" disabled={printing} onClick={()=>void print()}><Printer aria-hidden="true"/>{printing?t("ticketOperations.preparingPrint"):t("ticketOperations.print")}</button>:<p className="xto-print-warning">{t("ticketOperations.printDenied")}</p>}{printError?<p className="xto-print-warning" role="alert">{t("ticketOperations.printFailed")}</p>:null}</Section>
 </div></article>
}
