"use client";
import Link from "next/link"; import { ArrowRight, Search } from "lucide-react"; import { FormEvent, useEffect, useState } from "react";
import { useLanguage } from "@/i18n/LanguageProvider"; import { formatStaffDate } from "@/i18n/formatters"; import { cabinKey, statusKey } from "@/components/admin/tickets/ticketOperationsPresentation"; import type { TicketOperationsListItem,TicketOperationsPage } from "@/lib/admin/ticketOperationsTypes"; import "./ticketOperations.css";

const initial={ticketNumber:"",bookingReference:"",passengerName:"",flightNumber:"",origin:"",destination:"",travelDate:"",ticketStatus:"",cabin:""};
export function TicketsWorkspace(){
 const {locale,t}=useLanguage(); const [filters,setFilters]=useState(initial); const [items,setItems]=useState<TicketOperationsListItem[]>([]); const [nextOffset,setNextOffset]=useState<number|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [version,setVersion]=useState(0);
 const request=async(offset=0,append=false)=>{setLoading(true);setError(false);try{const response=await fetch("/admin/api/tickets/search",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json","x-x-fly-csrf":"1"},body:JSON.stringify({...filters,limit:50,offset})});if(!response.ok)throw new Error();const page=await response.json() as TicketOperationsPage;setItems(current=>append?[...current,...page.items]:page.items);setNextOffset(page.nextOffset);}catch{setError(true);}finally{setLoading(false);}};
 useEffect(()=>{const controller=new AbortController();fetch("/admin/api/tickets?limit=50&offset=0",{credentials:"same-origin",cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<TicketOperationsPage>}).then(p=>{setItems(p.items);setNextOffset(p.nextOffset)}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(true)}).finally(()=>setLoading(false));return()=>controller.abort()},[version]);
 const submit=(event:FormEvent)=>{event.preventDefault();void request()}; const update=(key:keyof typeof initial,value:string)=>setFilters(f=>({...f,[key]:value}));
 return <section className="xto-shell" aria-labelledby="ticket-ops-title"><header className="xto-header"><div className="xto-header-copy"><p>{t("ticketOperations.eyebrow")}</p><h1 id="ticket-ops-title">{t("ticketOperations.title")}</h1><span>{t("ticketOperations.intro")}</span></div><div className="xto-terminal"><span>XF / OPS—23</span><strong>{t("ticketOperations.terminal")}</strong></div></header>
 <form className="xto-filters" aria-label={t("ticketOperations.filters")} onSubmit={submit}><div className="xto-filter-grid">
 {(["ticketNumber","bookingReference","passengerName","flightNumber","origin","destination"] as const).map(key=><label key={key}><span>{t(`ticketOperations.${key}`)}</span><input autoComplete="off" value={filters[key]} onChange={e=>update(key,e.target.value)} /></label>)}
 <label><span>{t("ticketOperations.travelDate")}</span><input type="date" value={filters.travelDate} onChange={e=>update("travelDate",e.target.value)}/></label>
 <label><span>{t("ticketOperations.ticketStatus")}</span><select value={filters.ticketStatus} onChange={e=>update("ticketStatus",e.target.value)}><option value="">{t("ticketOperations.all")}</option><option value="ISSUED">ISSUED</option><option value="CANCELLED">CANCELLED</option></select></label>
 <label><span>{t("ticketOperations.cabin")}</span><select value={filters.cabin} onChange={e=>update("cabin",e.target.value)}><option value="">{t("ticketOperations.all")}</option><option value="BUSINESS">Business</option><option value="FIRST">First</option><option value="ECONOMY">Economy</option><option value="PREMIUM_ECONOMY">Premium Economy</option></select></label></div>
 <div className="xto-actions"><button type="submit" disabled={loading}><Search aria-hidden="true"/>{t("ticketOperations.search")}</button><button type="button" onClick={()=>{setFilters(initial);setVersion(v=>v+1)}}>{t("ticketOperations.reset")}</button></div></form>
 {loading&&!items.length?<p className="xto-state" role="status">{t("ticketOperations.loading")}</p>:null}{error?<div className="xto-state is-error" role="alert"><p>{t("ticketOperations.error")}</p><button onClick={()=>void request()}>{t("ticketOperations.retry")}</button></div>:null}
 {!loading&&!error&&!items.length?<div className="xto-state"><strong>{t("ticketOperations.empty")}</strong><p>{t("ticketOperations.emptyHelp")}</p></div>:null}
 {items.length?<div className="xto-table-wrap" role="region" tabIndex={0} aria-label={t("ticketOperations.title")}><table><caption className="sr-only">{t("ticketOperations.title")}</caption><thead><tr><th>{t("ticketOperations.ticketNumber")}</th><th>{t("ticketOperations.passenger")}</th><th>{t("ticketOperations.bookingReference")}</th><th>{t("ticketOperations.flight")}</th><th>{t("ticketOperations.route")}</th><th>{t("ticketOperations.travelDate")}</th><th>{t("ticketOperations.cabin")}</th><th>{t("ticketOperations.seat")}</th><th>{t("ticketOperations.ticketStatus")}</th><th>{t("ticketOperations.actions")}</th></tr></thead><tbody>{items.map(item=><tr key={item.ticketNumber}><th scope="row" className="xto-number">{item.ticketNumber}</th><td><strong>{item.passengerNames[0]}</strong>{item.passengerNames.length>1?<small>{t("ticketOperations.morePassengers",{count:item.passengerNames.length-1})}</small>:null}</td><td>{item.bookingReference}</td><td>{item.flightNumber}</td><td>{item.originCode} → {item.destinationCode}</td><td><time dateTime={item.travelDate}>{formatStaffDate(item.travelDate,locale)}</time></td><td>{t(cabinKey(item.cabin))}</td><td>{item.seats.join(" · ")}</td><td><span className={`xto-chip ${item.ticketStatus==="CANCELLED"?"is-cancelled":""}`}>{t(statusKey(item.ticketStatus))}</span></td><td><Link className="xto-open" href={`/admin/tickets/${item.ticketNumber}`} aria-label={`${t("ticketOperations.open")} ${item.ticketNumber}`}>{t("ticketOperations.open")}<ArrowRight aria-hidden="true"/></Link></td></tr>)}</tbody></table></div>:null}
 {nextOffset!==null?<button className="xto-more" disabled={loading} onClick={()=>void request(nextOffset,true)}>{t("ticketOperations.loadMore")}</button>:items.length?<p className="xto-end">{t("ticketOperations.end")}</p>:null}</section>
}
