-- X-Fly's curated supported-network master. This checked-in roster is the
-- deterministic authority in every environment: 156 ISO-coded countries and one
-- real primary commercial/international airport per country. Airport presence
-- describes network support only; scheduled flight inventory remains authoritative
-- for customer availability.
CREATE TABLE supported_countries (
    code TEXT PRIMARY KEY CHECK (code ~ '^[A-Z]{2}$'),
    name TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) > 0)
);

INSERT INTO supported_countries (code, name) VALUES
    ('AE', 'United Arab Emirates'),
    ('AF', 'Afghanistan'),
    ('AG', 'Antigua and Barbuda'),
    ('AL', 'Albania'),
    ('AM', 'Armenia'),
    ('AO', 'Angola'),
    ('AR', 'Argentina'),
    ('AT', 'Austria'),
    ('AU', 'Australia'),
    ('AZ', 'Azerbaijan'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BB', 'Barbados'),
    ('BD', 'Bangladesh'),
    ('BE', 'Belgium'),
    ('BF', 'Burkina Faso'),
    ('BG', 'Bulgaria'),
    ('BH', 'Bahrain'),
    ('BJ', 'Benin'),
    ('BN', 'Brunei'),
    ('BO', 'Bolivia'),
    ('BR', 'Brazil'),
    ('BS', 'Bahamas'),
    ('BW', 'Botswana'),
    ('BY', 'Belarus'),
    ('BZ', 'Belize'),
    ('CA', 'Canada'),
    ('CD', 'DR Congo'),
    ('CG', 'Congo'),
    ('CH', 'Switzerland'),
    ('CI', 'Côte d''Ivoire'),
    ('CL', 'Chile'),
    ('CM', 'Cameroon'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CR', 'Costa Rica'),
    ('CU', 'Cuba'),
    ('CV', 'Cape Verde'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czechia'),
    ('DE', 'Germany'),
    ('DJ', 'Djibouti'),
    ('DK', 'Denmark'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('DZ', 'Algeria'),
    ('EC', 'Ecuador'),
    ('EE', 'Estonia'),
    ('EG', 'Egypt'),
    ('ES', 'Spain'),
    ('ET', 'Ethiopia'),
    ('FI', 'Finland'),
    ('FJ', 'Fiji'),
    ('FR', 'France'),
    ('GA', 'Gabon'),
    ('GB', 'United Kingdom'),
    ('GD', 'Grenada'),
    ('GE', 'Georgia'),
    ('GH', 'Ghana'),
    ('GN', 'Guinea'),
    ('GQ', 'Equatorial Guinea'),
    ('GR', 'Greece'),
    ('GT', 'Guatemala'),
    ('HN', 'Honduras'),
    ('HR', 'Croatia'),
    ('HT', 'Haiti'),
    ('HU', 'Hungary'),
    ('ID', 'Indonesia'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IN', 'India'),
    ('IQ', 'Iraq'),
    ('IR', 'Iran'),
    ('IS', 'Iceland'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JO', 'Jordan'),
    ('JP', 'Japan'),
    ('KE', 'Kenya'),
    ('KG', 'Kyrgyzstan'),
    ('KN', 'Saint Kitts and Nevis'),
    ('KR', 'South Korea'),
    ('KW', 'Kuwait'),
    ('KZ', 'Kazakhstan'),
    ('LA', 'Laos'),
    ('LB', 'Lebanon'),
    ('LC', 'Saint Lucia'),
    ('LK', 'Sri Lanka'),
    ('LR', 'Liberia'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('LV', 'Latvia'),
    ('LY', 'Libya'),
    ('MA', 'Morocco'),
    ('ME', 'Montenegro'),
    ('MG', 'Madagascar'),
    ('MK', 'North Macedonia'),
    ('ML', 'Mali'),
    ('MM', 'Myanmar'),
    ('MR', 'Mauritania'),
    ('MT', 'Malta'),
    ('MU', 'Mauritius'),
    ('MV', 'Maldives'),
    ('MW', 'Malawi'),
    ('MX', 'Mexico'),
    ('MY', 'Malaysia'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibia'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('NI', 'Nicaragua'),
    ('NL', 'Netherlands'),
    ('NO', 'Norway'),
    ('NP', 'Nepal'),
    ('NZ', 'New Zealand'),
    ('OM', 'Oman'),
    ('PA', 'Panama'),
    ('PE', 'Peru'),
    ('PG', 'Papua New Guinea'),
    ('PH', 'Philippines'),
    ('PK', 'Pakistan'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PY', 'Paraguay'),
    ('RO', 'Romania'),
    ('RS', 'Serbia'),
    ('RU', 'Russia'),
    ('RW', 'Rwanda'),
    ('SA', 'Saudi Arabia'),
    ('SB', 'Solomon Islands'),
    ('SD', 'Sudan'),
    ('SE', 'Sweden'),
    ('SG', 'Singapore'),
    ('SI', 'Slovenia'),
    ('SK', 'Slovakia'),
    ('SL', 'Sierra Leone'),
    ('SO', 'Somalia'),
    ('SV', 'El Salvador'),
    ('TG', 'Togo'),
    ('TH', 'Thailand'),
    ('TJ', 'Tajikistan'),
    ('TM', 'Turkmenistan'),
    ('TN', 'Tunisia'),
    ('TR', 'Türkiye'),
    ('TT', 'Trinidad and Tobago'),
    ('TZ', 'Tanzania'),
    ('UG', 'Uganda'),
    ('US', 'United States'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('VU', 'Vanuatu'),
    ('YE', 'Yemen'),
    ('ZA', 'South Africa'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe');

ALTER TABLE airports
    ADD COLUMN is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    ADD CONSTRAINT airports_supported_country_fk
        FOREIGN KEY (country_code) REFERENCES supported_countries(code) ON DELETE RESTRICT;

INSERT INTO airports (code, name, city, country_code, time_zone, is_primary) VALUES
    ('DXB', 'Dubai International Airport', 'Dubai', 'AE', 'Asia/Dubai', TRUE),
    ('KBL', 'Kabul International Airport', 'Kabul', 'AF', 'Asia/Kabul', TRUE),
    ('ANU', 'V. C. Bird International Airport', 'Osbourn', 'AG', 'America/Antigua', TRUE),
    ('TIA', 'Tirana International Airport Mother Teresa', 'Rinas', 'AL', 'Europe/Tirane', TRUE),
    ('EVN', 'Zvartnots International Airport', 'Yerevan', 'AM', 'Asia/Yerevan', TRUE),
    ('LAD', 'Quatro de Fevereiro International Airport', 'Luanda', 'AO', 'Africa/Luanda', TRUE),
    ('EZE', 'Ezeiza International Airport - Ministro Pistarini', 'Buenos Aires (Ezeiza)', 'AR', 'America/Argentina/Buenos_Aires', TRUE),
    ('VIE', 'Vienna International Airport', 'Vienna', 'AT', 'Europe/Vienna', TRUE),
    ('SYD', 'Sydney Kingsford Smith International Airport', 'Sydney (Mascot)', 'AU', 'Australia/Sydney', TRUE),
    ('GYD', 'Heydar Aliyev International Airport', 'Baku', 'AZ', 'Asia/Baku', TRUE),
    ('SJJ', 'Sarajevo International Airport', 'Sarajevo', 'BA', 'Europe/Sarajevo', TRUE),
    ('BGI', 'Grantley Adams International Airport', 'Bridgetown', 'BB', 'America/Barbados', TRUE),
    ('DAC', 'Hazrat Shahjalal International Airport', 'Dhaka', 'BD', 'Asia/Dhaka', TRUE),
    ('BRU', 'Brussels Airport', 'Zaventem', 'BE', 'Europe/Brussels', TRUE),
    ('OUA', 'Ouagadougou Thomas Sankara International Airport', 'Ouagadougou', 'BF', 'Africa/Ouagadougou', TRUE),
    ('SOF', 'Sofia Airport', 'Sofia', 'BG', 'Europe/Sofia', TRUE),
    ('BAH', 'Bahrain International Airport', 'Manama', 'BH', 'Asia/Bahrain', TRUE),
    ('COO', 'Cotonou Cadjehoun International Airport', 'Cotonou', 'BJ', 'Africa/Porto-Novo', TRUE),
    ('BWN', 'Brunei International Airport', 'Bandar Seri Begawan', 'BN', 'Asia/Brunei', TRUE),
    ('LPB', 'El Alto International Airport', 'La Paz / El Alto', 'BO', 'America/La_Paz', TRUE),
    ('GRU', 'São Paulo/Guarulhos–Governor André Franco Montoro International Airport', 'São Paulo', 'BR', 'America/Sao_Paulo', TRUE),
    ('NAS', 'Lynden Pindling International Airport', 'Nassau', 'BS', 'America/Nassau', TRUE),
    ('GBE', 'Sir Seretse Khama International Airport', 'Gaborone', 'BW', 'Africa/Gaborone', TRUE),
    ('MSQ', 'Minsk National Airport', 'Minsk', 'BY', 'Europe/Minsk', TRUE),
    ('BZE', 'Philip S. W. Goldson International Airport', 'Belize City', 'BZ', 'America/Belize', TRUE),
    ('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'CA', 'America/Toronto', TRUE),
    ('FIH', 'Ndjili International Airport', 'Kinshasa', 'CD', 'Africa/Kinshasa', TRUE),
    ('BZV', 'Maya-Maya International Airport', 'Brazzaville', 'CG', 'Africa/Brazzaville', TRUE),
    ('ZRH', 'Zürich Airport', 'Zurich', 'CH', 'Europe/Zurich', TRUE),
    ('ABJ', 'Félix-Houphouët-Boigny International Airport', 'Abidjan', 'CI', 'Africa/Abidjan', TRUE),
    ('SCL', 'Comodoro Arturo Merino Benítez International Airport', 'Santiago', 'CL', 'America/Santiago', TRUE),
    ('DLA', 'Douala International Airport', 'Douala', 'CM', 'Africa/Douala', TRUE),
    ('PEK', 'Beijing Capital International Airport', 'Beijing', 'CN', 'Asia/Shanghai', TRUE),
    ('BOG', 'El Dorado International Airport', 'Bogota', 'CO', 'America/Bogota', TRUE),
    ('SJO', 'Juan Santamaría International Airport', 'San José (Alajuela)', 'CR', 'America/Costa_Rica', TRUE),
    ('HAV', 'José Martí International Airport', 'Havana', 'CU', 'America/Havana', TRUE),
    ('SID', 'Amílcar Cabral International Airport', 'Espargos', 'CV', 'Atlantic/Cape_Verde', TRUE),
    ('LCA', 'Larnaca International Airport', 'Larnaca', 'CY', 'Asia/Nicosia', TRUE),
    ('PRG', 'Václav Havel Airport Prague', 'Prague', 'CZ', 'Europe/Prague', TRUE),
    ('FRA', 'Frankfurt Main Airport', 'Frankfurt am Main', 'DE', 'Europe/Berlin', TRUE),
    ('JIB', 'Djibouti-Ambouli Airport', 'Djibouti City', 'DJ', 'Africa/Djibouti', TRUE),
    ('CPH', 'Copenhagen Kastrup Airport', 'Copenhagen', 'DK', 'Europe/Copenhagen', TRUE),
    ('DOM', 'Douglas-Charles Airport', 'Marigot', 'DM', 'America/Dominica', TRUE),
    ('PUJ', 'Punta Cana International Airport', 'Punta Cana', 'DO', 'America/Santo_Domingo', TRUE),
    ('ALG', 'Houari Boumediene Airport', 'Algiers', 'DZ', 'Africa/Algiers', TRUE),
    ('UIO', 'Mariscal Sucre International Airport', 'Quito', 'EC', 'America/Guayaquil', TRUE),
    ('TLL', 'Lennart Meri Tallinn Airport', 'Tallinn', 'EE', 'Europe/Tallinn', TRUE),
    ('CAI', 'Cairo International Airport', 'Cairo', 'EG', 'Africa/Cairo', TRUE),
    ('BCN', 'Josep Tarradellas Barcelona-El Prat Airport', 'Barcelona', 'ES', 'Europe/Madrid', TRUE),
    ('ADD', 'Addis Ababa Bole International Airport', 'Addis Ababa', 'ET', 'Africa/Addis_Ababa', TRUE),
    ('HEL', 'Helsinki Vantaa Airport', 'Helsinki (Vantaa)', 'FI', 'Europe/Helsinki', TRUE),
    ('NAN', 'Nadi International Airport', 'Nadi', 'FJ', 'Pacific/Fiji', TRUE),
    ('CDG', 'Charles de Gaulle International Airport', 'Paris (Roissy-en-France, Val-d''Oise)', 'FR', 'Europe/Paris', TRUE),
    ('LBV', 'Libreville Leon M''ba International Airport', 'Libreville', 'GA', 'Africa/Libreville', TRUE),
    ('LHR', 'Heathrow Airport', 'London', 'GB', 'Europe/London', TRUE),
    ('GND', 'Maurice Bishop International Airport', 'Saint George''s', 'GD', 'America/Grenada', TRUE),
    ('TBS', 'Tbilisi International Airport', 'Tbilisi', 'GE', 'Asia/Tbilisi', TRUE),
    ('ACC', 'Kotoka International Airport', 'Accra', 'GH', 'Africa/Accra', TRUE),
    ('CKY', 'Ahmed Sékou Touré International Airport', 'Conakry', 'GN', 'Africa/Conakry', TRUE),
    ('SSG', 'Malabo International Airport', 'Malabo', 'GQ', 'Africa/Malabo', TRUE),
    ('ATH', 'Athens Eleftherios Venizelos International Airport', 'Spata-Artemida', 'GR', 'Europe/Athens', TRUE),
    ('GUA', 'La Aurora International Airport', 'Guatemala City', 'GT', 'America/Guatemala', TRUE),
    ('SAP', 'Ramón Villeda Morales International Airport', 'San Pedro Sula', 'HN', 'America/Tegucigalpa', TRUE),
    ('DBV', 'Dubrovnik Ruđer Bošković Airport', 'Dubrovnik', 'HR', 'Europe/Zagreb', TRUE),
    ('PAP', 'Toussaint Louverture International Airport', 'Port-au-Prince', 'HT', 'America/Port-au-Prince', TRUE),
    ('BUD', 'Budapest Liszt Ferenc International Airport', 'Budapest', 'HU', 'Europe/Budapest', TRUE),
    ('CGK', 'Soekarno-Hatta International Airport', 'Jakarta', 'ID', 'Asia/Jakarta', TRUE),
    ('DUB', 'Dublin Airport', 'Dublin', 'IE', 'Europe/Dublin', TRUE),
    ('TLV', 'Ben Gurion International Airport', 'Tel Aviv', 'IL', 'Asia/Jerusalem', TRUE),
    ('DEL', 'Indira Gandhi International Airport', 'New Delhi', 'IN', 'Asia/Kolkata', TRUE),
    ('EBL', 'Erbil International Airport', 'Arbil', 'IQ', 'Asia/Baghdad', TRUE),
    ('MHD', 'Mashhad International Airport', 'Mashhad', 'IR', 'Asia/Tehran', TRUE),
    ('KEF', 'Keflavik International Airport', 'Reykjavík', 'IS', 'Atlantic/Reykjavik', TRUE),
    ('FCO', 'Rome–Fiumicino Leonardo da Vinci International Airport', 'Rome', 'IT', 'Europe/Rome', TRUE),
    ('MBJ', 'Sangster International Airport', 'Montego Bay', 'JM', 'America/Jamaica', TRUE),
    ('AMM', 'Queen Alia International Airport', 'Amman', 'JO', 'Asia/Amman', TRUE),
    ('HND', 'Haneda Airport', 'Tokyo', 'JP', 'Asia/Tokyo', TRUE),
    ('NBO', 'Jomo Kenyatta International Airport', 'Nairobi', 'KE', 'Africa/Nairobi', TRUE),
    ('OSS', 'Osh International Airport', 'Osh', 'KG', 'Asia/Bishkek', TRUE),
    ('SKB', 'Robert L. Bradshaw International Airport', 'Basseterre', 'KN', 'America/St_Kitts', TRUE),
    ('ICN', 'Incheon International Airport', 'Seoul', 'KR', 'Asia/Seoul', TRUE),
    ('KWI', 'Kuwait International Airport', 'Kuwait City', 'KW', 'Asia/Kuwait', TRUE),
    ('ALA', 'Almaty International Airport', 'Almaty', 'KZ', 'Asia/Almaty', TRUE),
    ('VTE', 'Wattay International Airport', 'Vientiane', 'LA', 'Asia/Vientiane', TRUE),
    ('BEY', 'Beirut Rafic Hariri International Airport', 'Beirut', 'LB', 'Asia/Beirut', TRUE),
    ('UVF', 'Hewanorra International Airport', 'Vieux Fort', 'LC', 'America/St_Lucia', TRUE),
    ('CMB', 'Bandaranaike International Colombo Airport', 'Colombo', 'LK', 'Asia/Colombo', TRUE),
    ('ROB', 'Roberts International Airport', 'Monrovia', 'LR', 'Africa/Monrovia', TRUE),
    ('VNO', 'Vilnius International Airport', 'Vilnius', 'LT', 'Europe/Vilnius', TRUE),
    ('LUX', 'Luxembourg-Findel International Airport', 'Luxembourg', 'LU', 'Europe/Luxembourg', TRUE),
    ('RIX', 'Riga International Airport', 'Riga', 'LV', 'Europe/Riga', TRUE),
    ('BEN', 'Benina International Airport', 'Benina', 'LY', 'Africa/Tripoli', TRUE),
    ('CMN', 'Mohammed V International Airport', 'Casablanca', 'MA', 'Africa/Casablanca', TRUE),
    ('TGD', 'Podgorica Airport / Podgorica Golubovci Airbase', 'Podgorica', 'ME', 'Europe/Podgorica', TRUE),
    ('TNR', 'Ivato International Airport', 'Antananarivo', 'MG', 'Indian/Antananarivo', TRUE),
    ('SKP', 'Skopje International Airport', 'Ilinden', 'MK', 'Europe/Skopje', TRUE),
    ('BKO', 'Modibo Keita International Airport', 'Bamako', 'ML', 'Africa/Bamako', TRUE),
    ('RGN', 'Yangon International Airport', 'Yangon', 'MM', 'Asia/Yangon', TRUE),
    ('NKC', 'Nouakchott–Oumtounsy International Airport', 'Nouakchott', 'MR', 'Africa/Nouakchott', TRUE),
    ('MLA', 'Malta International Airport', 'Valletta', 'MT', 'Europe/Malta', TRUE),
    ('MRU', 'Sir Seewoosagur Ramgoolam International Airport', 'Plaine Magnien', 'MU', 'Indian/Mauritius', TRUE),
    ('MLE', 'Velana International Airport', 'Malé', 'MV', 'Indian/Maldives', TRUE),
    ('LLW', 'Kamuzu International Airport', 'Lumbadzi', 'MW', 'Africa/Blantyre', TRUE),
    ('MEX', 'Mexico City Benito Juárez International Airport', 'Mexico City', 'MX', 'America/Mexico_City', TRUE),
    ('KUL', 'Kuala Lumpur International Airport', 'Sepang', 'MY', 'Asia/Kuala_Lumpur', TRUE),
    ('MPM', 'Maputo Airport', 'Maputo', 'MZ', 'Africa/Maputo', TRUE),
    ('WDH', 'Hosea Kutako International Airport', 'Windhoek', 'NA', 'Africa/Windhoek', TRUE),
    ('NIM', 'Diori Hamani International Airport', 'Niamey', 'NE', 'Africa/Niamey', TRUE),
    ('LOS', 'Murtala Muhammed International Airport', 'Lagos', 'NG', 'Africa/Lagos', TRUE),
    ('MGA', 'Augusto C. Sandino (Managua) International Airport', 'Managua', 'NI', 'America/Managua', TRUE),
    ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam', 'NL', 'Europe/Amsterdam', TRUE),
    ('OSL', 'Oslo-Gardermoen International Airport', 'Oslo (Gardermoen)', 'NO', 'Europe/Oslo', TRUE),
    ('KTM', 'Tribhuvan International Airport', 'Kathmandu', 'NP', 'Asia/Kathmandu', TRUE),
    ('AKL', 'Auckland International Airport', 'Auckland', 'NZ', 'Pacific/Auckland', TRUE),
    ('MCT', 'Muscat International Airport', 'Muscat/Seeb', 'OM', 'Asia/Muscat', TRUE),
    ('PTY', 'Tocumen International Airport', 'Tocumen', 'PA', 'America/Panama', TRUE),
    ('LIM', 'Jorge Chávez International Airport', 'Lima', 'PE', 'America/Lima', TRUE),
    ('POM', 'Port Moresby Jacksons International Airport', 'Port Moresby', 'PG', 'Pacific/Port_Moresby', TRUE),
    ('MNL', 'Ninoy Aquino International Airport', 'Manila (Pasay)', 'PH', 'Asia/Manila', TRUE),
    ('KHI', 'Jinnah International Airport', 'Karachi', 'PK', 'Asia/Karachi', TRUE),
    ('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'PL', 'Europe/Warsaw', TRUE),
    ('LIS', 'Lisbon Humberto Delgado Airport', 'Lisbon', 'PT', 'Europe/Lisbon', TRUE),
    ('ASU', 'Silvio Pettirossi International Airport', 'Asunción', 'PY', 'America/Asuncion', TRUE),
    ('OTP', 'Bucharest Henri Coandă International Airport', 'Otopeni', 'RO', 'Europe/Bucharest', TRUE),
    ('BEG', 'Belgrade Nikola Tesla Airport', 'Belgrade', 'RS', 'Europe/Belgrade', TRUE),
    ('DME', 'Domodedovo International Airport', 'Moscow', 'RU', 'Europe/Moscow', TRUE),
    ('KGL', 'Kigali International Airport', 'Kigali', 'RW', 'Africa/Kigali', TRUE),
    ('JED', 'King Abdulaziz International Airport', 'Jeddah', 'SA', 'Asia/Riyadh', TRUE),
    ('HIR', 'Honiara International Airport', 'Honiara', 'SB', 'Pacific/Guadalcanal', TRUE),
    ('KRT', 'Khartoum International Airport', 'Khartoum', 'SD', 'Africa/Khartoum', TRUE),
    ('ARN', 'Stockholm-Arlanda Airport', 'Stockholm', 'SE', 'Europe/Stockholm', TRUE),
    ('SIN', 'Singapore Changi Airport', 'Singapore', 'SG', 'Asia/Singapore', TRUE),
    ('LJU', 'Ljubljana Jože Pučnik Airport', 'Zgornji Brnik', 'SI', 'Europe/Ljubljana', TRUE),
    ('BTS', 'M. R. Štefánik Airport', 'Bratislava', 'SK', 'Europe/Bratislava', TRUE),
    ('FNA', 'Lungi International Airport', 'Freetown (Lungi-Town)', 'SL', 'Africa/Freetown', TRUE),
    ('MGQ', 'Aden Adde International Airport', 'Mogadishu', 'SO', 'Africa/Mogadishu', TRUE),
    ('SAL', 'El Salvador International Airport Saint Óscar Arnulfo Romero y Galdámez', 'San Salvador (San Luis Talpa)', 'SV', 'America/El_Salvador', TRUE),
    ('LFW', 'Lomé–Tokoin International Airport', 'Lomé', 'TG', 'Africa/Lome', TRUE),
    ('BKK', 'Suvarnabhumi Airport', 'Bangkok', 'TH', 'Asia/Bangkok', TRUE),
    ('DYU', 'Dushanbe International Airport', 'Dushanbe', 'TJ', 'Asia/Dushanbe', TRUE),
    ('ASB', 'Ashgabat International Airport', 'Ashgabat', 'TM', 'Asia/Ashgabat', TRUE),
    ('TUN', 'Tunis Carthage International Airport', 'Tunis', 'TN', 'Africa/Tunis', TRUE),
    ('SAW', 'Istanbul Sabiha Gökçen International Airport', 'Pendik, Istanbul', 'TR', 'Europe/Istanbul', TRUE),
    ('POS', 'Piarco International Airport', 'Port of Spain', 'TT', 'America/Port_of_Spain', TRUE),
    ('DAR', 'Julius Nyerere International Airport', 'Dar es Salaam', 'TZ', 'Africa/Dar_es_Salaam', TRUE),
    ('EBB', 'Entebbe International Airport', 'Entebbe', 'UG', 'Africa/Kampala', TRUE),
    ('JFK', 'John F. Kennedy International Airport', 'New York', 'US', 'America/New_York', TRUE),
    ('MVD', 'Carrasco General Cesáreo L. Berisso International Airport', 'Ciudad de la Costa', 'UY', 'America/Montevideo', TRUE),
    ('TAS', 'Tashkent International Airport', 'Tashkent', 'UZ', 'Asia/Tashkent', TRUE),
    ('CCS', 'Maiquetía Simón Bolívar International Airport', 'Maiquetía', 'VE', 'America/Caracas', TRUE),
    ('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', 'VN', 'Asia/Ho_Chi_Minh', TRUE),
    ('VLI', 'Bauerfield International Airport', 'Port Vila', 'VU', 'Pacific/Efate', TRUE),
    ('SAH', 'Sanaa International Airport', 'Sanaa', 'YE', 'Asia/Aden', TRUE),
    ('JNB', 'O.R. Tambo International Airport', 'Johannesburg', 'ZA', 'Africa/Johannesburg', TRUE),
    ('LUN', 'Kenneth Kaunda International Airport', 'Lusaka', 'ZM', 'Africa/Lusaka', TRUE),
    ('HRE', 'Robert Gabriel Mugabe International Airport', 'Harare', 'ZW', 'Africa/Harare', TRUE)
ON CONFLICT (code) DO NOTHING;

-- Preserve the original five valid airport records while designating the complete
-- curated roster as the primary supported network.
UPDATE airports SET is_primary = TRUE WHERE code IN (
    'ABJ', 'ACC', 'ADD', 'AKL', 'ALA', 'ALG', 'AMM', 'AMS', 'ANU', 'ARN', 'ASB', 'ASU',
    'ATH', 'BAH', 'BCN', 'BEG', 'BEN', 'BEY', 'BGI', 'BKK', 'BKO', 'BOG', 'BRU', 'BTS',
    'BUD', 'BWN', 'BZE', 'BZV', 'CAI', 'CCS', 'CDG', 'CGK', 'CKY', 'CMB', 'CMN', 'COO',
    'CPH', 'DAC', 'DAR', 'DBV', 'DEL', 'DLA', 'DME', 'DOM', 'DUB', 'DXB', 'DYU', 'EBB',
    'EBL', 'EVN', 'EZE', 'FCO', 'FIH', 'FNA', 'FRA', 'GBE', 'GND', 'GRU', 'GUA', 'GYD',
    'HAV', 'HEL', 'HIR', 'HND', 'HRE', 'ICN', 'JED', 'JFK', 'JIB', 'JNB', 'KBL', 'KEF',
    'KGL', 'KHI', 'KRT', 'KTM', 'KUL', 'KWI', 'LAD', 'LBV', 'LCA', 'LFW', 'LHR', 'LIM',
    'LIS', 'LJU', 'LLW', 'LOS', 'LPB', 'LUN', 'LUX', 'MBJ', 'MCT', 'MEX', 'MGA', 'MGQ',
    'MHD', 'MLA', 'MLE', 'MNL', 'MPM', 'MRU', 'MSQ', 'MVD', 'NAN', 'NAS', 'NBO', 'NIM',
    'NKC', 'OSL', 'OSS', 'OTP', 'OUA', 'PAP', 'PEK', 'POM', 'POS', 'PRG', 'PTY', 'PUJ',
    'RGN', 'RIX', 'ROB', 'SAH', 'SAL', 'SAP', 'SAW', 'SCL', 'SGN', 'SID', 'SIN', 'SJJ',
    'SJO', 'SKB', 'SKP', 'SOF', 'SSG', 'SYD', 'TAS', 'TBS', 'TGD', 'TIA', 'TLL', 'TLV',
    'TNR', 'TUN', 'UIO', 'UVF', 'VIE', 'VLI', 'VNO', 'VTE', 'WAW', 'WDH', 'YYZ', 'ZRH'
);

CREATE UNIQUE INDEX airports_one_primary_per_country_idx
    ON airports (country_code) WHERE is_primary;
CREATE INDEX airports_primary_search_idx
    ON airports (city, name, code) WHERE is_primary;
