export const bookingManagementEn = {
  eyebrow: "Service operations / X-Fly", title: "Booking Operations", intro: "Search, verify and safely service authoritative X-Fly reservations.", terminal: "Luxury Service Operations Terminal",
  filters: "Booking search and filters", filterTitle: "Find a reservation", bookingReference: "Booking Reference", passengerName: "Passenger name", flightNumber: "Flight number", travelDate: "Travel date", bookingStatus: "Booking status", flightStatus: "Flight status", cabin: "Cabin", origin: "Origin", destination: "Destination", all: "All", apply: "Search bookings", clear: "Reset filters",
  loading: "Loading authoritative bookings…", error: "Booking records are temporarily unavailable.", retry: "Try again", empty: "No bookings found", emptyHelp: "Adjust or reset the current filters.", loadMore: "Load more bookings", end: "End of results", open: "Open booking", lead: "Lead passenger", passengersCount: "{count} passengers", passengersCountOne: "1 passenger", bookedAt: "Booked", actions: "Action",
  booking: "Booking", journey: "Journey", passengers: "Passengers", contact: "Contact", payment: "Payment", ticket: "Ticket", cancellation: "Cancellation / Refund", audit: "Audit", back: "Back to bookings",
  route: "Route", departure: "Departure", aircraft: "Aircraft", seats: "Finalized seats", seatNote: "Seats are preserved as booking-level records; this schema does not store a passenger-to-seat mapping.", passengerType: "Passenger type", gender: "Gender", phone: "Phone", noContact: "No booking phone is stored.", method: "Method", provider: "Provider", statusLabel: "Status", amountPaid: "Amount paid", succeededAt: "Succeeded at", issuedAt: "Issued at", ticketNumber: "Ticket number", cancelledAt: "Cancelled at", refundStatus: "Refund state", refundAmount: "Refund amount", refundedAt: "Refunded at", eligibility: "Eligibility", cutoff: "Free-cancellation cutoff", noAudit: "No Booking Operations mutations recorded.", auditCancelled: "Staff booking cancellation", auditBy: "{action} by {actor}", unavailable: "Not available",
  status: { confirmed: "Confirmed", cancelled: "Cancelled", scheduled: "Scheduled", issued: "Issued", succeeded: "Succeeded", pending: "Pending", inFlight: "In flight", processing: "Processing", attention: "Requires attention", created: "Created", awaitingPayment: "Awaiting payment", failed: "Failed", eligible: "Eligible", ineligible: "Unavailable" },
  cabinName: { business: "Business", first: "First", economy: "Economy · historical", premiumEconomy: "Premium Economy · historical" }, historical: "Historical cabin",
  passenger: { adult: "Adult", child: "Child", infant: "Infant", male: "Male", female: "Female", unspecified: "Unspecified" },
  paymentMethod: { card: "Stripe Test Mode Card", bitcoin: "Mock Bitcoin", stripe: "Stripe · test mode", mockBitcoin: "Mock Bitcoin · deterministic demo" },
  flightCancelledNotice: "This flight is cancelled. The booking, payment and ticket remain separate authoritative records.",
  cancelBooking: "Cancel booking / full refund", cancelTitle: "Cancel booking {reference}?", cancelDescription: "This explicit action uses the same server-side 24-hour policy as customer cancellation.", consequence: "The ticket will be cancelled, active seat ownership released, and a 100% refund queued through the original test/demo payment method.", fullRefund: "100% refund", noFee: "Cancellation fee: THB 0", keep: "Keep booking", confirm: "Confirm cancellation", cancelling: "Cancelling…", cancelSuccess: "Booking cancelled. The returned authoritative refund state is shown below.", cancelFailed: "Cancellation was not completed. The booking was refreshed without assuming success.", notFound: "The exact booking was not found.", invalid: "Review the booking search values.", forbidden: "You do not have permission for this booking operation.", sessionExpired: "Your staff session has expired.", refresh: "Refresh booking",
} as const;

export const bookingManagementTh = {
  eyebrow: "ปฏิบัติการบริการ / X-Fly", title: "ปฏิบัติการการจอง", intro: "ค้นหา ตรวจสอบ และให้บริการรายการจอง X-Fly จากข้อมูลที่เชื่อถือได้อย่างปลอดภัย", terminal: "ศูนย์ปฏิบัติการบริการระดับพรีเมียม",
  filters: "การค้นหาและตัวกรองการจอง", filterTitle: "ค้นหารายการจอง", bookingReference: "รหัสการจอง", passengerName: "ชื่อผู้โดยสาร", flightNumber: "หมายเลขเที่ยวบิน", travelDate: "วันเดินทาง", bookingStatus: "สถานะการจอง", flightStatus: "สถานะเที่ยวบิน", cabin: "ชั้นโดยสาร", origin: "ต้นทาง", destination: "ปลายทาง", all: "ทั้งหมด", apply: "ค้นหาการจอง", clear: "ล้างตัวกรอง",
  loading: "กำลังโหลดข้อมูลการจองที่เชื่อถือได้…", error: "ข้อมูลการจองไม่พร้อมใช้งานชั่วคราว", retry: "ลองอีกครั้ง", empty: "ไม่พบการจอง", emptyHelp: "ปรับหรือล้างตัวกรองปัจจุบัน", loadMore: "โหลดการจองเพิ่ม", end: "สิ้นสุดผลลัพธ์", open: "เปิดการจอง", lead: "ผู้โดยสารหลัก", passengersCount: "ผู้โดยสาร {count} คน", passengersCountOne: "ผู้โดยสาร 1 คน", bookedAt: "จองเมื่อ", actions: "การดำเนินการ",
  booking: "การจอง", journey: "การเดินทาง", passengers: "ผู้โดยสาร", contact: "ข้อมูลติดต่อ", payment: "การชำระเงิน", ticket: "ตั๋วโดยสาร", cancellation: "การยกเลิก / คืนเงิน", audit: "บันทึกตรวจสอบ", back: "กลับไปการจอง",
  route: "เส้นทาง", departure: "ออกเดินทาง", aircraft: "เครื่องบิน", seats: "ที่นั่งที่ยืนยันแล้ว", seatNote: "ระบบเก็บที่นั่งในระดับการจอง และโครงสร้างข้อมูลนี้ไม่ได้เก็บการจับคู่ผู้โดยสารกับที่นั่ง", passengerType: "ประเภทผู้โดยสาร", gender: "เพศ", phone: "โทรศัพท์", noContact: "ไม่มีหมายเลขโทรศัพท์ของการจอง", method: "วิธีชำระ", provider: "ผู้ให้บริการ", statusLabel: "สถานะ", amountPaid: "ยอดชำระ", succeededAt: "ชำระสำเร็จเมื่อ", issuedAt: "ออกตั๋วเมื่อ", ticketNumber: "หมายเลขตั๋ว", cancelledAt: "ยกเลิกเมื่อ", refundStatus: "สถานะคืนเงิน", refundAmount: "ยอดคืนเงิน", refundedAt: "คืนเงินเมื่อ", eligibility: "สิทธิ์ยกเลิก", cutoff: "เวลาสิ้นสุดการยกเลิกฟรี", noAudit: "ยังไม่มีการเปลี่ยนแปลงโดยฝ่ายปฏิบัติการการจอง", auditCancelled: "พนักงานยกเลิกการจอง", auditBy: "{action} โดย {actor}", unavailable: "ไม่มีข้อมูล",
  status: { confirmed: "ยืนยันแล้ว", cancelled: "ยกเลิกแล้ว", scheduled: "ตามกำหนด", issued: "ออกตั๋วแล้ว", succeeded: "สำเร็จ", pending: "รอดำเนินการ", inFlight: "กำลังดำเนินงาน", processing: "กำลังประมวลผล", attention: "ต้องตรวจสอบ", created: "สร้างแล้ว", awaitingPayment: "รอชำระเงิน", failed: "ล้มเหลว", eligible: "ยกเลิกได้", ineligible: "ไม่สามารถยกเลิกได้" },
  cabinName: { business: "ชั้นธุรกิจ", first: "ชั้นหนึ่ง", economy: "ชั้นประหยัด · ข้อมูลเดิม", premiumEconomy: "ชั้นประหยัดพรีเมียม · ข้อมูลเดิม" }, historical: "ชั้นโดยสารในอดีต",
  passenger: { adult: "ผู้ใหญ่", child: "เด็ก", infant: "ทารก", male: "ชาย", female: "หญิง", unspecified: "ไม่ระบุ" },
  paymentMethod: { card: "บัตร Stripe โหมดทดสอบ", bitcoin: "Bitcoin จำลอง", stripe: "Stripe · โหมดทดสอบ", mockBitcoin: "Bitcoin จำลอง · การสาธิตแบบกำหนดแน่นอน" },
  flightCancelledNotice: "เที่ยวบินนี้ถูกยกเลิก แต่การจอง การชำระเงิน และตั๋วยังคงเป็นข้อมูลที่เชื่อถือได้คนละส่วน",
  cancelBooking: "ยกเลิกการจอง / คืนเงินเต็มจำนวน", cancelTitle: "ยกเลิกการจอง {reference} หรือไม่", cancelDescription: "การดำเนินการนี้ใช้กฎ 24 ชั่วโมงจากเซิร์ฟเวอร์เดียวกับการยกเลิกของลูกค้า", consequence: "ตั๋วจะถูกยกเลิก สิทธิ์ที่นั่งปัจจุบันจะถูกปล่อย และระบบจะจัดคิวคืนเงิน 100% ผ่านวิธีชำระเงินทดสอบ/จำลองเดิม", fullRefund: "คืนเงิน 100%", noFee: "ค่าธรรมเนียมยกเลิก: 0 บาท", keep: "คงการจองไว้", confirm: "ยืนยันการยกเลิก", cancelling: "กำลังยกเลิก…", cancelSuccess: "ยกเลิกการจองแล้ว สถานะคืนเงินล่าสุดจากระบบแสดงด้านล่าง", cancelFailed: "การยกเลิกไม่สำเร็จ ระบบรีเฟรชข้อมูลการจองโดยไม่แสดงผลสำเร็จล่วงหน้า", notFound: "ไม่พบการจองตามรหัสที่ระบุ", invalid: "โปรดตรวจสอบค่าค้นหาการจอง", forbidden: "คุณไม่มีสิทธิ์ดำเนินการนี้กับการจอง", sessionExpired: "เซสชันพนักงานหมดอายุแล้ว", refresh: "รีเฟรชการจอง",
} as const;
