export const dashboardEn = {
  eyebrow: "Owner intelligence / X-Fly", title: "Commercial performance", titleLineOne: "Commercial", titleLineTwo: "Performance", intro: "Every number grounded in authoritative booking records.", decorativeRoute: "Decorative commercial trajectory / not geographic data",
  summary: "Executive summary", revenue: "Gross Booking Revenue", bookings: "Total Bookings", tickets: "Tickets Issued", average: "Average Booking Value",
  cancellationRate: "Cancellation Rate", refunds: "Refund Value", refundCount: "Completed refunds", cancelled: "Cancelled bookings",
  today: "Today", seven: "7 days", thirty: "30 days", month: "This month", from: "From", to: "To", route: "Route", cabin: "Cabin", allRoutes: "All routes", allCabins: "All cabins", provider: "Payment records", apply: "Apply filters", cohortControls: "Commercial cohort controls", updating: "Updating intelligence", updatingShort: "Updating",
  stripe: "Stripe · test mode", mockBitcoin: "Mock Bitcoin · demo", source: "Stored test/demo payment records · THB only · not live cash receipts",
  basis: "Booking cohort by payment success date · Bangkok time (UTC+7). Revenue includes taxes, fees and extras, before refunds. Refunds and cancellations reflect the current status of these bookings, even when processed later.",
  commandDeck: "Commercial command", marketSignal: "Market", demandSignal: "Pulse", grossQualifier: "Gross value before refunds", revenueTrend: "Gross booking revenue trend", demandTrend: "Booking demand trend", daily: "Daily activity", chartTable: "View daily figures", chartInspectionInstructions: "Inspect daily values. Use Left and Right Arrow to move by day, Home for the first day, and End for the last day.", tooltipDate: "Date", tooltipRevenue: "Gross Booking Revenue", tooltipBookings: "Bookings", date: "Date", revenueShort: "Revenue", bookingsShort: "Bookings",
  routeTitle: "Where demand takes flight", routeSubtitle: "Top 10 commercial corridors by gross booking revenue", cabinTitle: "Cabin intelligence", cabinChart: "Instrumented cabin mix by bookings", cabinTotal: "Recorded mix", cabinSubtitle: "Share of successful bookings, not passengers", economy: "Economy", premiumEconomy: "Premium Economy", business: "Business", first: "First",
  recoveryTitle: "Recovery intelligence", recoverySubtitle: "Operational state of cancellations and refunds in this cohort", completed: "Completed", pending: "Pending / processing", attention: "Requires attention", pendingValue: "Pending refund value", statusRecorded: "Recorded state", reviewState: "Review state", clearState: "No attention required",
  flightTitle: "Flight performance", flightSubtitle: "Commercial ranking by recorded successful bookings", rankingView: "Flight ranking view", rank: "Rank", mostBooked: "Most booked", highestRevenue: "Highest revenue", flight: "Flight / departure", inventoryTitle: "Recorded seat occupancy", inventorySubtitle: "A capacity instrument for current recorded inventory", inventoryNote: "Booked ÷ sellable seats for recorded departures, across all payment providers. Inventory is created on demand; unrecorded flights are excluded. This is not fleet-wide load factor.", lowDemand: "Lowest recorded occupancy", seats: "Booked / sellable", booked: "booked", sellable: "sellable", occupancy: "Occupancy", occupancyLabel: "Recorded occupancy {percent}: {booked} booked seats from {sellable} sellable seats",
  briefCode: "Brief", insights: "Executive brief", insightsNote: "Calculated from this selection", leadingRoute: "{route} leads gross revenue with {share}% of the selected total.", leadingCabin: "{cabin} accounts for {share}% of successful bookings.", refundInsight: "{count} refunds require attention in this booking cohort.", noInsights: "Observations will appear when this selection has successful bookings.",
  loading: "Loading commercial performance", loadingDetail: "Aligning the selected booking cohort and recorded inventory.", refreshError: "The latest selection could not be loaded. The previous snapshot remains visible.", emptyCode: "No data", empty: "No successful bookings in this selection.", emptyHelp: "Try a wider date range or another payment source. Recorded inventory may still be available below.", noRows: "No records in this selection.", error: "Commercial performance is temporarily unavailable.", retry: "Try again", unauthenticated: "Your staff session has expired.", signIn: "Sign in again", forbidden: "You do not have permission to view executive analytics.", workspace: "Return to workspace", invalid: "Choose a valid date range of no more than 366 days.", refreshed: "Snapshot", range: "Selected period", unavailable: "Not available",
} as const;

export const dashboardTh: { [K in keyof typeof dashboardEn]: string } = {
  eyebrow: "ข้อมูลสำหรับเจ้าของกิจการ / X-Fly", title: "ผลการดำเนินงานเชิงพาณิชย์", titleLineOne: "ผลการดำเนินงาน", titleLineTwo: "เชิงพาณิชย์", intro: "ทุกตัวเลขมาจากข้อมูลการจองที่เชื่อถือได้และบันทึกไว้ในระบบ", decorativeRoute: "เส้นวิถีเชิงพาณิชย์เพื่อการตกแต่ง / ไม่ใช่ข้อมูลภูมิศาสตร์",
  summary: "สรุปสำหรับผู้บริหาร", revenue: "รายได้รวมจากการจอง", bookings: "จำนวนการจองทั้งหมด", tickets: "ตั๋วที่ออกแล้ว", average: "มูลค่าการจองเฉลี่ย",
  cancellationRate: "อัตราการยกเลิก", refunds: "มูลค่าการคืนเงิน", refundCount: "รายการคืนเงินสำเร็จ", cancelled: "การจองที่ยกเลิก",
  today: "วันนี้", seven: "7 วัน", thirty: "30 วัน", month: "เดือนนี้", from: "ตั้งแต่", to: "ถึง", route: "เส้นทาง", cabin: "ชั้นโดยสาร", allRoutes: "ทุกเส้นทาง", allCabins: "ทุกชั้นโดยสาร", provider: "แหล่งข้อมูลการชำระเงิน", apply: "ใช้ตัวกรอง", cohortControls: "ตัวควบคุมกลุ่มข้อมูลเชิงพาณิชย์", updating: "กำลังปรับข้อมูลวิเคราะห์", updatingShort: "กำลังอัปเดต",
  stripe: "Stripe · โหมดทดสอบ", mockBitcoin: "Bitcoin จำลอง · สาธิต", source: "ข้อมูลการชำระเงินทดสอบ/สาธิตที่บันทึกไว้ · เฉพาะ THB · ไม่ใช่เงินรับจริง",
  basis: "จัดกลุ่มการจองตามวันที่ชำระเงินสำเร็จ · เวลากรุงเทพฯ (UTC+7) รายได้รวมภาษี ค่าธรรมเนียม และบริการเสริม ก่อนหักเงินคืน การคืนเงินและการยกเลิกแสดงสถานะปัจจุบันของกลุ่มการจองนี้ แม้ดำเนินการภายหลัง",
  commandDeck: "ศูนย์บัญชาการเชิงพาณิชย์", marketSignal: "ตลาด", demandSignal: "จังหวะความต้องการ", grossQualifier: "มูลค่ารวมก่อนหักเงินคืน", revenueTrend: "แนวโน้มรายได้รวมจากการจอง", demandTrend: "แนวโน้มจำนวนการจอง", daily: "กิจกรรมรายวัน", chartTable: "ดูตัวเลขรายวัน", chartInspectionInstructions: "ตรวจสอบค่ารายวัน ใช้ปุ่มลูกศรซ้ายและขวาเพื่อเลื่อนทีละวัน ปุ่ม Home สำหรับวันแรก และ End สำหรับวันสุดท้าย", tooltipDate: "วันที่", tooltipRevenue: "รายได้รวมจากการจอง", tooltipBookings: "การจอง", date: "วันที่", revenueShort: "รายได้", bookingsShort: "การจอง",
  routeTitle: "เส้นทางแห่งความต้องการ", routeSubtitle: "10 เส้นทางเชิงพาณิชย์อันดับแรกตามรายได้รวมจากการจอง", cabinTitle: "ข้อมูลเชิงลึกของชั้นโดยสาร", cabinChart: "เครื่องมือแสดงสัดส่วนชั้นโดยสารตามการจอง", cabinTotal: "สัดส่วนที่บันทึก", cabinSubtitle: "สัดส่วนการจองที่สำเร็จ ไม่ใช่จำนวนผู้โดยสาร", economy: "ชั้นประหยัด", premiumEconomy: "ชั้นประหยัดพรีเมียม", business: "ชั้นธุรกิจ", first: "ชั้นหนึ่ง",
  recoveryTitle: "ข้อมูลการยกเลิกและคืนเงิน", recoverySubtitle: "สถานะการดำเนินงานของการยกเลิกและคืนเงินในกลุ่มนี้", completed: "สำเร็จแล้ว", pending: "รอดำเนินการ / กำลังดำเนินการ", attention: "ต้องตรวจสอบ", pendingValue: "มูลค่าเงินคืนที่รอดำเนินการ", statusRecorded: "สถานะที่บันทึก", reviewState: "สถานะรอตรวจสอบ", clearState: "ไม่มีรายการต้องตรวจสอบ",
  flightTitle: "ผลการดำเนินงานรายเที่ยวบิน", flightSubtitle: "การจัดอันดับเชิงพาณิชย์จากการจองที่สำเร็จและบันทึกไว้", rankingView: "มุมมองการจัดอันดับเที่ยวบิน", rank: "อันดับ", mostBooked: "จองมากที่สุด", highestRevenue: "รายได้สูงสุด", flight: "เที่ยวบิน / วันออกเดินทาง", inventoryTitle: "อัตราที่นั่งที่จองในข้อมูลที่บันทึก", inventorySubtitle: "เครื่องมือแสดงความจุจากข้อมูลที่นั่งปัจจุบัน", inventoryNote: "ที่นั่งที่จอง ÷ ที่นั่งที่ขายได้ของเที่ยวบินที่บันทึกไว้ รวมทุกผู้ให้บริการชำระเงิน ระบบสร้างข้อมูลที่นั่งเมื่อมีการใช้งาน ไม่รวมเที่ยวบินที่ยังไม่ถูกบันทึก จึงไม่ใช่อัตราบรรทุกผู้โดยสารทั้งฝูงบิน", lowDemand: "เที่ยวบินที่มีอัตราการจองต่ำสุดในข้อมูล", seats: "จองแล้ว / ขายได้", booked: "ที่จอง", sellable: "ที่ขายได้", occupancy: "อัตราการจองที่นั่ง", occupancyLabel: "อัตราการจองที่นั่งที่บันทึก {percent}: จองแล้ว {booked} ที่นั่ง จากที่นั่งที่ขายได้ {sellable} ที่นั่ง",
  briefCode: "สรุป", insights: "บทสรุปสำหรับผู้บริหาร", insightsNote: "คำนวณจากข้อมูลที่เลือก", leadingRoute: "{route} มีรายได้รวมสูงสุด คิดเป็น {share}% ของยอดที่เลือก", leadingCabin: "{cabin} คิดเป็น {share}% ของการจองที่สำเร็จ", refundInsight: "มีรายการคืนเงิน {count} รายการที่ต้องตรวจสอบในกลุ่มการจองนี้", noInsights: "ข้อสังเกตจะแสดงเมื่อมีการจองที่สำเร็จในข้อมูลที่เลือก",
  loading: "กำลังโหลดผลการดำเนินงานเชิงพาณิชย์", loadingDetail: "กำลังจัดกลุ่มข้อมูลการจองที่เลือกและข้อมูลที่นั่งที่บันทึกไว้", refreshError: "ไม่สามารถโหลดตัวเลือกล่าสุดได้ ข้อมูลก่อนหน้ายังคงแสดงอยู่", emptyCode: "ไม่มีข้อมูล", empty: "ไม่มีการจองที่สำเร็จในข้อมูลที่เลือก", emptyHelp: "ลองขยายช่วงวันที่หรือเลือกแหล่งข้อมูลการชำระเงินอื่น ข้อมูลที่นั่งที่บันทึกไว้อาจยังแสดงด้านล่าง", noRows: "ไม่มีข้อมูลในช่วงที่เลือก", error: "ไม่สามารถโหลดผลการดำเนินงานเชิงพาณิชย์ได้ในขณะนี้", retry: "ลองอีกครั้ง", unauthenticated: "เซสชันพนักงานหมดอายุแล้ว", signIn: "เข้าสู่ระบบอีกครั้ง", forbidden: "คุณไม่มีสิทธิ์เข้าถึงข้อมูลวิเคราะห์สำหรับผู้บริหาร", workspace: "กลับไปพื้นที่ทำงาน", invalid: "เลือกช่วงวันที่ที่ถูกต้องและไม่เกิน 366 วัน", refreshed: "ข้อมูล ณ", range: "ช่วงเวลาที่เลือก", unavailable: "ไม่มีข้อมูล",
};
