const en = {
  common: {
    cabins: { business: "Business", economy: "Economy", first: "First", premiumEconomy: "Premium Economy", premiumEconomyShort: "Premium" },
    closeDialog: "Close dialog", direct: "Direct", farePerPassenger: "Sample fare · per passenger", oneStop: "1 stop", oneWay: "One way", passenger: "passenger", passengers: "passengers", returnDate: "Return {date}", to: "to",
  },
  flightDetail: {
    aircraft: "Aircraft",
    aircraftFeatures: { airframe: "High-efficiency airframe", filtration: "Modern air filtration", quiet: "Quiet cabin", widebody: "Long-haul widebody" },
    back: "Back to Flights",
    cabin: { chooseSeat: "Choose Your Seat", description: "Explore four distinct cabin experiences before choosing your seat.", experienceLabel: "Cabin experience", heading: "Choose how you want to fly.", label: "Cabin", notAvailable: "Not available on this flight", previewAnother: "Preview another cabin to continue.", searched: "your searched cabin", unavailable: "Unavailable", unavailableLower: "unavailable", yourSearch: "Your search" },
    cabinContent: {
      business: { alt: "Business Class lie-flat pod and private side console aboard X-Fly", description: "Space to focus, dine, and arrive ready.", feature1: "Lie-flat seat", feature2: "Direct aisle access", feature3: "Premium dining" },
      economy: { alt: "Economy cabin seating aboard X-Fly with spacious rows and aircraft windows", description: "Practical comfort shaped for an effortless journey.", feature1: "Practical comfort", feature2: "Standard recline", feature3: "Personal entertainment" },
      first: { alt: "First Class private suite with luxury dining and personalized setting aboard X-Fly", description: "A private expression of flight, considered in every detail.", feature1: "Private suite", feature2: "Maximum personal space", feature3: "Signature service" },
      premiumEconomy: { alt: "Premium Economy seating aboard X-Fly with expanded width and legroom", description: "More room and calm for the distance ahead.", feature1: "Wider seat", feature2: "More legroom", feature3: "Enhanced service" },
    },
    chooseSeatAria: "Choose your seat in {cabin} on flight {flight}", chooseSeatUnavailableAria: "Choose your seat in {cabin} on flight {flight}, unavailable", localTimes: "All times shown in local airport time.", onSchedule: "On schedule",
  },
  flightResults: {
    availableFlightsLabel: "Available outbound flights", departureTime: "Departure Time", duration: "Duration", emptyDescription: "Try adjusting your date, route, or cabin.", emptyTitle: "No flights found", flightCount: "{count} flights available", flightCountOne: "1 flight available", label: "Flight results", localTimes: "All times shown in local airport time.", modifySearch: "Modify Search", outbound: "Outbound", price: "Price", recommended: "Recommended", requiredDescription: "Return to Flight Search to choose your itinerary.", requiredTitle: "Search details required", routeCities: "{from} to {to}", selectFlight: "Select Flight", selectFlightAria: "Select flight {flight}", selectOutbound: "Select your outbound flight", sortFlights: "Sort flights",
  },
  flightSearch: {
    airport: { chooseDestination: "Choose destination", chooseOrigin: "Choose origin", description: "Choose from featured Earth destinations. Availability is not live.", featured: "Featured airports", from: "From", matching: "Matching airports", noMatch: "No featured airports match your search.", placeholder: "Code, city, airport, or country", search: "Search airport or city", selectDestination: "Select destination", selectOrigin: "Select origin", to: "To" },
    cabin: "Cabin", cabinClass: "Cabin class", departureDate: "Departure date", eyebrow: "Flight search · Earth routes", formLabel: "Search Earth flights", heading: "Where will you go next?", intro: "Choose your route and shape the journey in a few precise steps.",
    passenger: { adultDescription: "12+ years", adults: "Adults", childDescription: "2–11 years", children: "Children", count: "{count} passengers", countOne: "1 passenger", decrease: "Decrease {label}", description: "Choose who is travelling. At least one adult is required.", increase: "Increase {label}", infants: "Infants", label: "Passengers", safety: "99 per category is a UI safety guard, not an airline policy.", totalAria: "Passengers, {count} total", underTwo: "Under 2 years" },
    returnDate: "Return date", reviewErrors: "Review the highlighted fields before searching.", search: "Search Flights", searchReady: "Search criteria ready. Flight results will be available in the next step.", swap: "Swap origin and destination",
    trip: { legend: "Trip type", oneWay: "One Way", roundTrip: "Round Trip" },
    validation: { adultRequired: "At least one adult is required.", departurePast: "Departure date cannot be in the past.", departureRequired: "Choose a departure date.", departureValid: "Choose a valid departure date.", destinationDifferent: "Origin and destination must be different.", destinationRequired: "Choose a destination.", originRequired: "Choose an origin.", passengerRange: "Passenger counts are outside the supported UI range.", returnOrder: "Return date must be on or after departure.", returnRequired: "Choose a return date.", returnValid: "Choose a valid return date." },
  },
  footer: { about: "About X-Fly", cabins: "Cabins", company: "Company", copyright: "© 2026 X-Fly Anyway.", description: "A premium global aviation experience designed for what comes next.", designed: "Designed to go anywhere.", explore: "Explore", help: "Help Centre", legal: "Legal", manageBooking: "Manage Booking", offers: "Offers", privacy: "Privacy", support: "Support", terms: "Terms", travel: "Travel" },
  home: {
    promo: { carouselLabel: "Featured promotions", goToSlide: "Go to promotion {number}", next: "Next promotion", paginationLabel: "Promotion pagination", previous: "Previous promotion", slideAria: "Promotion {current} of {total}", slides: { premium: { action: "Explore the cabin", body: "A quieter, more personal expression of the journey—designed for arrival as much as departure.", heading: "Travel, elevated.", label: "X-Fly Signature", meta: "Business Class · Selected routes" }, earlyBooking: { action: "Plan your journey", body: "Set your plans in motion with considered fares for the cities and moments ahead.", heading: "Book early. Go further.", label: "Advance fares", meta: "Limited release · Earth routes" }, family: { action: "Discover family travel", body: "More room for every generation to settle in, look forward, and travel with ease.", heading: "The journey is for everyone.", label: "Family moments", meta: "Seasonal journeys · Selected dates" } } },
    aircraft: { body: "More than a route between two places. A journey with one considered rhythm from takeoff to arrival.", controlLabel: "Aircraft narrative milestones", eyebrow: "The X-Fly way", global: { copy: "One connected journey across continents and time zones.", headline: "GO FURTHER.", label: "GLOBAL" }, goTo: "Go to {label}", heading: "Movement, made personal.", personal: { copy: "Space shaped around how you choose to travel.", headline: "FLY YOUR WAY.", label: "PERSONAL" }, premium: { copy: "Thoughtful comfort, considered at every altitude.", headline: "ABOVE THE ORDINARY.", label: "PREMIUM" }, seamless: { copy: "Every detail considered from departure to arrival.", headline: "FROM HERE TO THERE.", label: "SEAMLESS" } },
    cabins: { business: { alt: "Business Class lie-flat pod and private side console aboard X-Fly", copy: "Space to focus. Freedom to arrive ready." }, controlLabel: "Cabin choices", economy: { alt: "Economy cabin seating aboard X-Fly with spacious rows and aircraft windows", copy: "Ease, considered from departure to arrival." }, first: { alt: "First Class private suite with luxury dining and personalized setting aboard X-Fly", copy: "A private expression of flight." }, goTo: "Go to {label}", heading: "Choose your way to fly.", intro: "One standard of confidence, expressed across four distinct journeys.", label: "Four ways forward", premiumEconomy: { alt: "Premium Economy seating aboard X-Fly with expanded width and legroom", copy: "More room for the distance ahead." } },
    experience: { body: "Every detail is shaped to give the journey back to you—from the first decision to the final arrival.", choice: "Choice", comfort: "Comfort", control: "Control", heading: "Designed around the journey.", label: "The X-Fly experience" },
    hero: { body: "From the world’s great cities to what comes next. Travel without limits.", eyebrow: "X-FLY ANYWAY · GLOBAL AVIATION", explore: "Explore X-Fly", headline: "Go anywhere. Fly different.", scroll: "Scroll", scrollAria: "Scroll to explore X-Fly" },
    journey: {
      arrive: { body: "Arrival should feel as composed as the journey itself.", headline: "A seamless arrival.", imageCity: "City arrival and premium hospitality", imageTraveler: "Traveler arriving at a premium city hotel", label: "CHAPTER 3 · ARRIVE" },
      begin: { body: "Every considered journey begins before departure.", headline: "Where the journey begins.", imageDocuments: "Passport and premium travel documents", imageLounge: "Traveler preparing to depart from an airport lounge", label: "CHAPTER 1 · BEGIN" },
      heading: "A continuous journey.", label: "X-Fly Journey",
      move: { body: "Comfort and clarity, carried through every mile.", headline: "One considered path.", imageCabin: "Traveler in a private premium cabin", imageWindow: "Business traveler looking through an aircraft window", label: "CHAPTER 2 · MOVE" },
    },
    service: { body: "Thoughtful service, refined comfort, and a sense of ease from the moment you board.", cabinAlt: "X-Fly premium cabin with an ivory seat and dining setting", cabinBody: "Space designed to let the journey feel effortless.", cabinHeading: "Cabin comfort", cabinLabel: "01 · Interior", headingFirst: "A journey considered", headingSecond: "in every detail.", label: "X-FLY SERVICE", serviceAlt: "X-Fly cabin crew providing an onboard dining service", serviceBody: "Care that feels considered, never excessive.", serviceHeading: "Personal service", serviceLabel: "02 · Service" },
  },
  loading: { flightDetail: "Loading flight detail", flightResults: "Loading flight results", seatMap: "Loading seat map" },
  navigation: { bookFlight: "Book a Flight", cabins: "Cabins", closeMenu: "Close navigation menu", dialogDescription: "X-Fly Anyway public navigation.", experience: "Experience", explore: "Explore", home: "X-Fly Anyway home", languageToggle: "Current language: English. Switch to Thai.", menuTitle: "Navigation", mobile: "Mobile navigation", offers: "Offers", openMenu: "Open navigation menu", primary: "Primary navigation", tagline: "Global aviation · Designed to go anywhere" },
  passengerInformation: {
    addEmergency: "Add emergency contact", back: "Back to seats", chooseCountry: "Choose a country", choosePhoneCountry: "Choose a phone country code", contact: "Contact details", continueEditing: "Edit passenger information", emergency: "Emergency contact", eyebrow: "Your journey · Passenger details", formLabel: "Passenger information form", heading: "Passenger information", identity: "Identity", infantNoSeat: "Infant · No seat assigned", intro: "Enter each traveller exactly as shown on their passport.", loading: "Loading passenger information", nameWarning: "Name must match passport exactly.", nextPassenger: "Next passenger", optional: "Optional", passengerNav: "Passengers", passport: "Passport details", previousPassenger: "Previous passenger", removeEmergency: "Remove emergency contact", required: "Required", returnSeats: "Return to seat selection", save: "Save passenger information", savedReady: "Passenger information saved and ready for the next step.", saving: "Saving passenger information…", seats: "Held seats", summary: "Journey summary",
    countrySelector: { emergencyPhoneLabel: "Phone country code emergency contact", noResults: "No countries found.", searchLabel: "Search countries", searchPlaceholder: "Search countries" },
    field: { dateOfBirth: "Date of birth", email: "Email", emergencyName: "Contact name", familyName: "Family name", gender: "Gender", givenName: "Given name", middleName: "Middle name", nationality: "Nationality", passportIssuingCountry: "Passport issuing country", passportNumber: "Passport number", phoneCountryCode: "Phone country code", phoneNumber: "Phone number", relationship: "Relationship", title: "Title" },
    gender: { female: "Female", male: "Male", unspecified: "Unspecified" },
    passenger: { adult: "Adult", child: "Child", infant: "Infant", label: "Passenger {ordinal} — {type}" },
    progress: { extras: "Extras", passenger: "Passenger", seat: "Seat" },
    state: { expired: "Your seat hold expired. Return to seat selection to choose seats again.", invalid: "This passenger link is invalid.", released: "Your seat hold was released. Return to seat selection to choose seats again.", unauthorized: "This seat hold cannot be accessed. Return to seat selection.", unavailable: "Passenger information is temporarily unavailable. Please try again." },
    title: { mr: "Mr", ms: "Ms" },
    validation: { ageCategory: "Date of birth does not match this passenger type.", duplicatePassport: "Each passenger must use a different passport number.", emergencyIncomplete: "Complete all emergency contact fields or remove the contact.", invalidCountry: "Choose a valid country.", invalidDate: "Enter a valid date.", invalidEmail: "Enter a valid email address.", invalidName: "Use letters and standard name punctuation only.", invalidPassport: "Enter a valid passport number.", invalidPhone: "Enter a valid country code and phone number.", required: "This field is required.", review: "Review the highlighted passenger fields.", futureBirth: "Date of birth cannot be in the future." },
  },
  seatMap: {
    abbreviations: { door: "Door", exit: "Exit", galley: "G", lavatory: "Lav" },
    aircraftFront: "Aircraft front", aircraftOverview: "{aircraft} aircraft overview, {section} highlighted for {cabin}", aircraftPlan: "Aircraft plan", aircraftSectionFeatures: "Aircraft section features", available: "Available", back: "Back to Flight", booked: "Booked", bulkhead: "Bulkhead",
    columnGuides: { business: "Window A · Aisle · D G · Aisle · K Window", economy: "Window · A B C · Aisle · D E F · Window", first: "Private suite A · Aisle · Private suite K", premiumEconomy: "Window · A C · Aisle · D F · Window" },
    continue: "Continue", continueAria: "Continue with {count} seats", continueAriaOne: "Continue with 1 seat", continueValidating: "Checking your seats…", deselect: "Deselect a seat before choosing another.", front: "Front", holdConfirmed: "Your seat hold is confirmed.", holdConflict: "That seat was just taken. Choose another seat.", holdCountdown: "Seats held for {time}", holdExpired: "Your seat hold expired. Select your seat again.", holdIncomplete: "Hold the required number of seats before continuing.", holdServiceUnavailable: "Seat availability could not be confirmed. Please try again.", lapInfant: "lap infant", legend: "Seat legend",
    marker: { bulkhead: "Cabin bulkhead", centralCabin: "Central cabin", door1: "Door 1", door2: "Door 2", exit: "Exit", foremostCabin: "Foremost cabin", forwardCabin: "Forward cabin", forwardGalley: "Forward galley", lavatory: "Lavatory", midRearCabin: "Mid-rear cabin", overwingExit: "Overwing exit", rearExit: "Rear exit", rearGalley: "Rear galley", wingArea: "Wing area", wingLeading: "Wing leading area" },
    noSeats: "No seats selected", notEnoughBody: "This local cabin fixture has {available} selectable seats, but this booking requires {required}. Return to the flight to choose another cabin.", notEnoughTitle: "Not enough fixture seats", passengerCount: "{count} passengers", passengerCountOne: "1 passenger", position: { aisle: "aisle", middle: "middle", window: "window" }, rear: "Rear", rowAria: "Row {row}", seatAria: "Seat {seat}, {cabin}, {position}, {status}", seatMapUnavailableBody: "This cabin does not have a local seat layout. Return to the flight to choose another cabin.", seatMapUnavailableTitle: "Seat map unavailable", seatRowsAria: "{cabin} seat rows", selected: "Selected", selectedCount: "{selected} of {required} seats selected", selectedCountOne: "{selected} of 1 seat selected", selectRequirement: "Select {count} seats", selectRequirementOne: "Select 1 seat", selectSeatsToProceed: "Continue, select {count} seats to proceed", selectSeatToProceed: "Continue, select 1 seat to proceed", selectYourSeat: "Select your seat", status: { available: "available", booked: "booked", selected: "selected", unavailable: "unavailable" }, swipe: "Swipe within the aircraft section to view every seat.", unavailable: "Unavailable", yourSeats: "Your seats",
  },
} as const;

export { en };
