export const flightManagementEn = {
  eyebrow: "Precision operations / X-Fly", title: "Flight Management", intro: "Authoritative schedules, inventory and sellable cabin configuration.", flightOperations: "Flight Operations", filterTitle: "Filter / Find service", serviceRegistry: "Flight service registry",
  create: "Create flight", readOnly: "Read-only access", loading: "Loading flights", error: "Flight management is temporarily unavailable.", retry: "Try again", empty: "No flights match these filters.",
  filters: "Flight filters", flightNumber: "Flight number", origin: "Origin", destination: "Destination", departureDate: "Departure date", status: "Status", all: "All", apply: "Apply filters", clear: "Clear filters",
  flight: "Flight", route: "Route", departure: "Departure", cabins: "Cabins", aircraft: "Aircraft", actions: "Actions", view: "View flight", scheduled: "Scheduled", cancelled: "Cancelled", recurring: "Recurring schedule", localTime: "Local airport time", businessFirst: "Business / First",
  loadMore: "Load more flights", showing: "Showing {count} of {total} flights",
  identity: "Identity", schedule: "Schedule", inventory: "Aircraft / Inventory", commercial: "Commercial", audit: "Audit / History", serviceConfiguration: "Service Configuration", operationalSummary: "Operational flight summary", newService: "XF / New service", aircraftPending: "Aircraft pending", routePending: "Route pending", business: "Business", first: "First",
  save: "Save flight", saving: "Saving…", saved: "Flight saved.", edit: "Edit flight", back: "Back to flights", cancelFlight: "Cancel flight", cancelling: "Cancelling…",
  cancelTitle: "Cancel {flight}?", cancelDescription: "{route} departing {departure} will become unavailable for all new searches, holds and payments. Existing records remain preserved.", keepScheduled: "Keep scheduled", confirmCancel: "Confirm flight cancellation", cancelSyncWarning: "Flight was cancelled, but the latest history could not be loaded. Refresh this detail later.",
  businessPrice: "Business price (THB)", firstPrice: "First price (THB)", businessCapacity: "Business capacity", firstCapacity: "First capacity", arrival: "Arrival", nextDay: "Arrives next day", aircraftContext: "Aircraft context", chooseAirport: "Choose airport", searchAirport: "Search airport", noAirportsFound: "No airports found", chooseAircraft: "Choose aircraft",
  validation: "Review the highlighted flight fields.", conflict: "This flight changed or has materialized customer inventory. Reload before trying again.", forbidden: "You do not have permission to change flights.", notFound: "The flight was not found.", unavailable: "Not available", noAudit: "No mutation history is available.", createdBy: "{action} by {actor}", actionCreated: "Flight created", actionEdited: "Flight edited", actionCancelled: "Flight cancelled",
} as const;

export const flightManagementTh: { [K in keyof typeof flightManagementEn]: string } = {
  eyebrow: "ปฏิบัติการแม่นยำ / X-Fly", title: "การจัดการเที่ยวบิน", intro: "จัดการตารางบิน ที่นั่ง และชั้นโดยสารที่จำหน่ายจากข้อมูลจริง", flightOperations: "ปฏิบัติการเที่ยวบิน", filterTitle: "ตัวกรอง / ค้นหาเที่ยวบิน", serviceRegistry: "ทะเบียนเที่ยวบิน", create: "สร้างเที่ยวบิน", readOnly: "สิทธิ์อ่านอย่างเดียว", loading: "กำลังโหลดเที่ยวบิน", error: "ระบบจัดการเที่ยวบินไม่พร้อมใช้งานชั่วคราว", retry: "ลองอีกครั้ง", empty: "ไม่พบเที่ยวบินที่ตรงกับตัวกรอง",
  filters: "ตัวกรองเที่ยวบิน", flightNumber: "หมายเลขเที่ยวบิน", origin: "ต้นทาง", destination: "ปลายทาง", departureDate: "วันออกเดินทาง", status: "สถานะ", all: "ทั้งหมด", apply: "ใช้ตัวกรอง", clear: "ล้างตัวกรอง", flight: "เที่ยวบิน", route: "เส้นทาง", departure: "ออกเดินทาง", cabins: "ชั้นโดยสาร", aircraft: "เครื่องบิน", actions: "การดำเนินการ", view: "ดูเที่ยวบิน", scheduled: "ตามกำหนด", cancelled: "ยกเลิกแล้ว", recurring: "ตารางบินประจำ", localTime: "เวลาท้องถิ่นของสนามบิน", businessFirst: "ชั้นธุรกิจ / ชั้นหนึ่ง", loadMore: "โหลดเที่ยวบินเพิ่ม", showing: "แสดง {count} จาก {total} เที่ยวบิน",
  identity: "ข้อมูลเที่ยวบิน", schedule: "ตารางเวลา", inventory: "เครื่องบิน / ที่นั่ง", commercial: "ราคา", audit: "ประวัติการเปลี่ยนแปลง", serviceConfiguration: "การกำหนดค่าเที่ยวบิน", operationalSummary: "สรุปข้อมูลเที่ยวบิน", newService: "XF / เที่ยวบินใหม่", aircraftPending: "ยังไม่ระบุเครื่องบิน", routePending: "ยังไม่ระบุเส้นทาง", business: "ชั้นธุรกิจ", first: "ชั้นหนึ่ง", save: "บันทึกเที่ยวบิน", saving: "กำลังบันทึก…", saved: "บันทึกเที่ยวบินแล้ว", edit: "แก้ไขเที่ยวบิน", back: "กลับไปเที่ยวบิน", cancelFlight: "ยกเลิกเที่ยวบิน", cancelling: "กำลังยกเลิก…", cancelTitle: "ยกเลิก {flight} หรือไม่", cancelDescription: "{route} ออกเดินทาง {departure} จะไม่พร้อมสำหรับการค้นหา การถือที่นั่ง และการชำระเงินใหม่ โดยยังเก็บรักษาข้อมูลเดิมไว้", keepScheduled: "คงเที่ยวบินไว้", confirmCancel: "ยืนยันยกเลิกเที่ยวบิน", cancelSyncWarning: "ยกเลิกเที่ยวบินแล้ว แต่ไม่สามารถโหลดประวัติล่าสุดได้ กรุณารีเฟรชรายละเอียดในภายหลัง", businessPrice: "ราคาชั้นธุรกิจ (บาท)", firstPrice: "ราคาชั้นหนึ่ง (บาท)", businessCapacity: "จำนวนที่นั่งชั้นธุรกิจ", firstCapacity: "จำนวนที่นั่งชั้นหนึ่ง", arrival: "ถึงปลายทาง", nextDay: "ถึงวันถัดไป", aircraftContext: "ข้อมูลเครื่องบิน", chooseAirport: "เลือกสนามบิน", searchAirport: "ค้นหาสนามบิน", noAirportsFound: "ไม่พบสนามบิน", chooseAircraft: "เลือกเครื่องบิน", validation: "โปรดตรวจสอบข้อมูลเที่ยวบินที่ระบุ", conflict: "เที่ยวบินนี้มีการเปลี่ยนแปลงหรือมีข้อมูลที่นั่งแล้ว โปรดโหลดใหม่ก่อนลองอีกครั้ง", forbidden: "คุณไม่มีสิทธิ์เปลี่ยนแปลงเที่ยวบิน", notFound: "ไม่พบเที่ยวบิน", unavailable: "ไม่มีข้อมูล", noAudit: "ยังไม่มีประวัติการเปลี่ยนแปลง", createdBy: "{action} โดย {actor}", actionCreated: "สร้างเที่ยวบิน", actionEdited: "แก้ไขเที่ยวบิน", actionCancelled: "ยกเลิกเที่ยวบิน",
};
