export const ticketOperationsEn={
  eyebrow:"Travel document operations / X-Fly",title:"Ticket / Passenger Operations",intro:"Locate and inspect authoritative passenger and E-ticket records.",terminal:"Luxury Travel Document Operations Terminal",
  filters:"Ticket and passenger search",ticketNumber:"Ticket Number",bookingReference:"Booking Reference",passengerName:"Passenger name",flightNumber:"Flight Number",origin:"Origin",destination:"Destination",travelDate:"Travel date",ticketStatus:"Ticket status",cabin:"Cabin",all:"All",search:"Search records",reset:"Reset filters",
  loading:"Loading authoritative ticket records…",empty:"No ticket records found",emptyHelp:"Review or reset the operational filters.",error:"Ticket records are temporarily unavailable.",retry:"Try again",loadMore:"Load more",end:"End of results",passenger:"Passenger",flight:"Flight",route:"Route",seat:"Seat",actions:"Action",open:"Inspect ticket",morePassengers:"+{count} more",
  back:"Back to tickets",ticket:"Ticket",passengers:"Passengers",journey:"Journey",travelProduct:"Travel product",booking:"Booking",document:"Document",issuedAt:"Issued at",cancelledAt:"Cancelled at",passengerType:"Passenger type",gender:"Gender",paymentStatus:"Payment status",bookingStatus:"Booking status",flightStatus:"Flight status",refundStatus:"Refund status",departure:"Departure",timeZone:"Schedule time zone",unavailable:"Not available",historical:"Historical",legacyGender:"Legacy / historical value",noSeat:"Infant · no seat",
  print:"Print E-ticket",preparingPrint:"Preparing secure document…",printDenied:"You do not have permission to print this ticket.",printFailed:"The printable ticket is unavailable.",cancelledPrint:"Cancelled tickets remain inspectable but cannot be printed as active travel documents.",cancelledNotice:"CANCELLED — not valid for travel",flightCancelledTitle:"FLIGHT CANCELLED",flightCancelledMessage:"This E-ticket remains an authoritative historical travel document. The associated flight is cancelled and this document does not represent an active scheduled journey.",qrLabel:"Signed X-Fly ticket verification QR",qrContext:"Backend-signed verification QR. It contains no passenger personal data.",documentTitle:"X-FLY E-TICKET",documentCopy:"Existing authoritative travel document · not a Boarding Pass",
  status:{issued:"Issued",cancelled:"Cancelled",confirmed:"Confirmed",scheduled:"Scheduled",succeeded:"Succeeded",pending:"Pending",processing:"Processing",inFlight:"In flight",attention:"Requires attention",created:"Created",awaitingPayment:"Awaiting payment",failed:"Failed"},
  cabinName:{business:"Business",first:"First",economy:"Economy · historical",premiumEconomy:"Premium Economy · historical"}, passengerTypeName:{adult:"Adult",child:"Child",infant:"Infant"},genderName:{male:"Male",female:"Female",unspecified:"Unspecified · historical"},
  notFound:"The exact ticket was not found.",invalid:"Review the ticket search values.",forbidden:"You do not have permission to access these passenger and ticket records.",sessionExpired:"Your staff session has expired."
} as const;

export const ticketOperationsTh:{[K in keyof typeof ticketOperationsEn]:typeof ticketOperationsEn[K] extends string?string:{[P in keyof typeof ticketOperationsEn[K]]:string}}={
  eyebrow:"ปฏิบัติการเอกสารการเดินทาง / X-Fly",title:"ปฏิบัติการตั๋วและผู้โดยสาร",intro:"ค้นหาและตรวจสอบข้อมูลผู้โดยสารและตั๋วอิเล็กทรอนิกส์ที่เชื่อถือได้",terminal:"ศูนย์ปฏิบัติการเอกสารการเดินทางระดับพรีเมียม",
  filters:"ค้นหาตั๋วและผู้โดยสาร",ticketNumber:"หมายเลขตั๋ว",bookingReference:"รหัสการจอง",passengerName:"ชื่อผู้โดยสาร",flightNumber:"หมายเลขเที่ยวบิน",origin:"ต้นทาง",destination:"ปลายทาง",travelDate:"วันเดินทาง",ticketStatus:"สถานะตั๋ว",cabin:"ชั้นโดยสาร",all:"ทั้งหมด",search:"ค้นหาข้อมูล",reset:"ล้างตัวกรอง",
  loading:"กำลังโหลดข้อมูลตั๋วที่เชื่อถือได้…",empty:"ไม่พบข้อมูลตั๋ว",emptyHelp:"ตรวจสอบหรือล้างตัวกรองการค้นหา",error:"ข้อมูลตั๋วไม่พร้อมใช้งานชั่วคราว",retry:"ลองอีกครั้ง",loadMore:"โหลดเพิ่ม",end:"สิ้นสุดผลลัพธ์",passenger:"ผู้โดยสาร",flight:"เที่ยวบิน",route:"เส้นทาง",seat:"ที่นั่ง",actions:"การดำเนินการ",open:"ตรวจสอบตั๋ว",morePassengers:"อีก {count} คน",
  back:"กลับไปยังตั๋ว",ticket:"ตั๋ว",passengers:"ผู้โดยสาร",journey:"การเดินทาง",travelProduct:"ผลิตภัณฑ์การเดินทาง",booking:"การจอง",document:"เอกสาร",issuedAt:"ออกตั๋วเมื่อ",cancelledAt:"ยกเลิกเมื่อ",passengerType:"ประเภทผู้โดยสาร",gender:"เพศ",paymentStatus:"สถานะชำระเงิน",bookingStatus:"สถานะการจอง",flightStatus:"สถานะเที่ยวบิน",refundStatus:"สถานะคืนเงิน",departure:"ออกเดินทาง",timeZone:"เขตเวลาตารางบิน",unavailable:"ไม่มีข้อมูล",historical:"ข้อมูลในอดีต",legacyGender:"ค่าเดิม / ข้อมูลในอดีต",noSeat:"ทารก · ไม่มีที่นั่ง",
  print:"พิมพ์ตั๋วอิเล็กทรอนิกส์",preparingPrint:"กำลังเตรียมเอกสารที่ปลอดภัย…",printDenied:"คุณไม่มีสิทธิ์พิมพ์ตั๋วนี้",printFailed:"เอกสารตั๋วสำหรับพิมพ์ไม่พร้อมใช้งาน",cancelledPrint:"ตั๋วที่ยกเลิกแล้วยังคงตรวจสอบได้ แต่ไม่สามารถพิมพ์เป็นเอกสารเดินทางที่ใช้งานได้",cancelledNotice:"ยกเลิกแล้ว — ใช้เดินทางไม่ได้",flightCancelledTitle:"เที่ยวบินถูกยกเลิก",flightCancelledMessage:"ตั๋วอิเล็กทรอนิกส์นี้ยังคงเป็นเอกสารการเดินทางในอดีตที่เชื่อถือได้ เที่ยวบินที่เกี่ยวข้องถูกยกเลิก และเอกสารนี้ไม่ได้แสดงถึงการเดินทางตามกำหนดการที่ยังใช้งานอยู่",qrLabel:"QR ตรวจสอบตั๋ว X-Fly ที่ลงนามแล้ว",qrContext:"QR ตรวจสอบที่ลงนามโดยแบ็กเอนด์ ไม่มีข้อมูลส่วนบุคคลของผู้โดยสาร",documentTitle:"ตั๋วอิเล็กทรอนิกส์ X-FLY",documentCopy:"เอกสารเดินทางที่เชื่อถือได้เดิม · ไม่ใช่บัตรขึ้นเครื่อง",
  status:{issued:"ออกตั๋วแล้ว",cancelled:"ยกเลิกแล้ว",confirmed:"ยืนยันแล้ว",scheduled:"ตามกำหนด",succeeded:"สำเร็จ",pending:"รอดำเนินการ",processing:"กำลังประมวลผล",inFlight:"กำลังดำเนินงาน",attention:"ต้องตรวจสอบ",created:"สร้างแล้ว",awaitingPayment:"รอชำระเงิน",failed:"ล้มเหลว"},
  cabinName:{business:"ชั้นธุรกิจ",first:"ชั้นหนึ่ง",economy:"ชั้นประหยัด · ข้อมูลเดิม",premiumEconomy:"ชั้นประหยัดพรีเมียม · ข้อมูลเดิม"},passengerTypeName:{adult:"ผู้ใหญ่",child:"เด็ก",infant:"ทารก"},genderName:{male:"ชาย",female:"หญิง",unspecified:"ไม่ระบุ · ข้อมูลเดิม"},
  notFound:"ไม่พบตั๋วตามหมายเลขที่ระบุ",invalid:"โปรดตรวจสอบค่าค้นหาตั๋ว",forbidden:"คุณไม่มีสิทธิ์เข้าถึงข้อมูลผู้โดยสารและตั๋วเหล่านี้",sessionExpired:"เซสชันพนักงานหมดอายุแล้ว"
};
